name: Mod Suggestion
description: A template for suggesting mod ideas
labels: Needs Categorization
body:
  - type: markdown
    attributes:
      value: >-
        ## Description

        Explain what you want the mod to do, attach images if necessary

        - Have you used the [search
        tool](https://github.com/martmists-gh/fabric-mod-wishlist/issues) to make sure you are not opening a duplicate?
  - type: dropdown
    attributes:
      options:
      - Forge
      - Fabric
      label: Mod loader
      description: Froge
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: 'Example: The Piston should extend.'
    validations:
      required: true     

### Description
### <!-- . -->
### Details
### - Does a Forge version of this mod exist? <yes/no>
###    - If yes, what is the link to the github/curseforge? <link>
### - Does a Fabric version of this mod exist for an older MC version? <yes/no>
###    - If yes, what is the link to the github/curseforge? <link>
