name: Mod Suggestion
description: A template for suggesting mod ideas
labels: Needs Categorization
body:
  - type: markdown
    attributes:
      value: >-
        ## Instructions


        Add a description of what you want the mod to do, attach images if necessary

        - Have you used the [search
        tool](https://github.com/CaffeineMC/sodium-fabric/issues) to find
        similar issues? If you find one that looks like what you are getting,
        consider contributing additional information to it instead. Make sure
        you are not opening a duplicate.

  - type: input
    id: version
    attributes:
      label: Version information
      description: >-
        Please provide the exact version of the mod you are using. Every part of
        the version is important! If you do not know what version you are using,
        look at the file name in your `mods` folder.
      placeholder: 'Example: mc1.16.4-0.1.1+rev.4b3964a'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: 'Example: The Piston should extend.'
    validations:
      required: true     

### Description
### <!-- . -->
### Details
### - Does a Forge version of this mod exist? <yes/no>
###    - If yes, what is the link to the github/curseforge? <link>
### - Does a Fabric version of this mod exist for an older MC version? <yes/no>
###    - If yes, what is the link to the github/curseforge? <link>
